# Generated by Django 3.1.3 on 2021-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('solved', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
