# Generated by Django 3.1.3 on 2021-07-24 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'mp3', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='image',
            name='solved',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
