# Generated by Django 3.1.3 on 2021-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210724_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='solved',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
